version: '2'

services:
  orca:
    build:
      context: .
      dockerfile: ./5.1.0-bionic/Dockerfile
    image: jma-receipt:5.1.0-bionic
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      # !! Please change ormaster password !!
      ORMASTER_PASS: ormaster
      ORMASTER_PASS_RESET: "false"
      ORCA_DB_HOST: db
      ORCA_DB_PORT: 5432
      #ORCA_DB_ENCODING: UTF-8
      # !! Please change DB user and password !!
      # Also change PostgreSQL container (see below)
      ORCA_DB_NAME: orca
      ORCA_DB_USER: orca
      ORCA_DB_PASS: orca_password
    volumes:
      - orca_data:/data

  db:
    image: postgres:10-alpine
    environment:
      TZ: Asia/Tokyo
      # Please change DB user and password, same as above.
      POSTGRES_USER: orca
      POSTGRES_PASSWORD: orca_password
      POSTGRES_INITDB_ARGS: "--no-locale --encoding=EUC_JP"
      #POSTGRES_INITDB_ARGS: "--no-locale --encoding=UTF-8"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  orca_data:
  pg_data:

networks:
  default:
