version: '3'

services:
  orca:
    image: harukats/jma-receipt
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      # ORMASTER_PASS: ormaster
      # ORMASTER_PASS_RESET: "false"
      ORCA_DB_HOST: db
      ORCA_DB_PORT: 5432
      ORCA_DB_NAME: orca
      ORCA_DB_USER: orca
      ORCA_DB_PASS: orca_password
      # ORCA_DB_ENCODING: UTF-8
    volumes:
      - orca_data:/data

  db:
    image: postgres:10-alpine
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: orca
      POSTGRES_PASSWORD: orca_password
      POSTGRES_INITDB_ARGS: "--no-locale --encoding=EUC_JP"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  orca_data:
  pg_data:
